### ISSUE TITLE
qemu with kvm support?

### ISSUE THREAD

**Issue by mkurmag** [TUD-OS/NUL#25] opened 2013-10-07 17:04 UTC
When I add -enable-kvm to qemu run's options, I get
`NOVA Microhypervisor v6-82da1aa (x86_32): Oct  7 2013 18:18:24 [gcc 4.8.1]
Task gate invoked`
I look in [src/idt.cpp](https://github.com/TUD-OS/NOVA/blob/master/src/idt.cpp) and add `if (vector==8)` before 33 line. And I get same error. So something call interrupt at 8 vector.
If i run qemu without -enable-kvm everything works fine.

qemu 1.6.0. OS archlinux.

**Comment by Nils-TUD** [comment] 2013-10-15 08:41
I think, this has nothing to do with NUL, but only with NOVA. Although it is not NOVA's fault. This seems to be a qemu/kvm bug, because it works fine on real hardware. I had this a while ago as well. Currently, qemu doesn't even start to execute the BIOS as it seems, if I enable kvm (with 3.8.0-30-generic). Really strange :/
What Linux kernel version do you have?
@blitz You said, it works for you, right?

**Comment by mkurmag** [comment] 2013-10-15 09:18
I've ran qemu with different options and find out that with option "-cpu qemu64 -enable-kvm" everything works fine. 

PS Amd, Linux version is 3.11.4-1.

**Comment by blitz** [comment] 2013-10-15 10:43
I missed this issue. One possible reason could be that NOVA doesn't check CPUID flags for the instructions it uses. I'll check that once Fedora updates Qemu to 1.6.

**Comment by udosteinberg** [comment] 2013-10-15 22:56
Could it be this?: https://bugs.launchpad.net/qemu/+bug/720657

**Comment by blitz** [comment] 2013-10-18 12:35
@mkurmag Can you tell me how to reproduce this problem exactly?

**Comment by mkurmag** [comment] 2013-10-18 13:13
in michal/boot/vancouver file I set `QEMU_FLAGS= -cpu host -enable-kvm -smp 2` and run it and it output that I write in first message . I tried also `-cpu phenom -enable-kvm` and it as far as I remember (I won't have access to that amd machine until monday) it output that cpu doesn't have svm option. 

Also I'm trying run NUL on qemu kvm in intel machine, But it is not working. First I enable nested virtualization in kernel:

```
# modprobe -r kvm_intel 
# modprobe kvm_intel nested=1
```

so after run qemu (without NUL) `-cpu host -enable-kvm` or `-cpu qemu64,+vmx -enable-kvm` there is option "vmx" in `/proc/cpuinfo` file. But when I try run NUL with that options for qemu it output `creating a VCPU failed - does your CPU support VMX/SVM`.

**Comment by udosteinberg** [comment] 2013-10-18 13:40
Presence of the VMX feature flag in CPUID is not sufficient. VMXON checks certain bits in IA32_FEATURE_CONTROL MSR and the NOVA microhypervisor checks those bits as well. Maybe KVM is not implementing that MSR correctly. See https://github.com/IntelLabs/NOVA/blob/master/src/vmx.cpp#L102

**Comment by blitz** [comment] 2013-10-19 13:05
VMX in KVM only works with a small NOVA patch. See: https://github.com/TUD-OS/NOVA/issues/1

**Comment by blitz** [comment] 2013-10-19 13:09
@mkurmag If it fails for you with `-cpu host`, can you post /proc/cpuinfo content from this box?

**Comment by mkurmag** [comment] 2013-10-21 10:45
@blitz If I understand you right, you ask content /proc/cpuinfo in AMD machine (where `-cpu host` fails and `-cpu qemu64` works). I run `qemu-system-x86_64 -cpu host -enable-kvm --initrd initrd-js.lzma -kernel bzImage-js -serial stdio`

/proc/cpuinfo:

```
processor   : 0
vendor_id   : AuthenticAMD
cpu family  : 16
model       : 4
model name  : AMD Phenom(tm) II X4 980 Processor
stepping    : 3
cpu MHz     : 3700.117
cache size  : 512 KB
fdiv_bug    : no
hlt_bug     : no
f00f_bug    : no
coma_bug    : no
fpu     : yes
fpu_exception   : yes
cpuid level : 5
wp      : yes
flags       : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 syscall nx mmxext fxsr_opt pdpe1gb lm 3dnowext 3dnow up extd_apicid pni cx16 x2apic popcnt hypervisor lahf_lm cmp_legacy svm cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw npt nrip_save
bogomips    : 7400.23
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```

Previous path for NOVA I'll try little later on Intel machine.

**Comment by udosteinberg** [comment] 2013-10-21 11:01
Looks like it's reporting SVM as a feature, because that is supported by the host CPU. So NOVA should be enabling SVM with `-cpu host` whereas if you run `-cpu qemu64,+vmx` you would advertise VMX features.

**Comment by mkurmag** [comment] 2013-10-21 12:07
Sorry if I make it unclear. I have 2 machines AMD(with svm) and Interl(with vmx) and I tried run NUL on both machines. AMD is prefered for me. 
In AMD machine I can make NOVA run only by `-cpu qemu64 -enable-kvm` option and with `-cpu host -enable-kvm` option it doesn't run and displays what wrote in first message. 
In Intel machine I can't make it run, even by `-cpu qemu64,+vmx -enable-kvm` option. I haven't try NOVA's patch for VMX support yet.

**Comment by mkurmag** [comment] 2013-10-23 09:28
Tested with vmx patch on Intel machine. It works

**Comment by blitz** [comment] 2013-10-28 13:24
That VMX works only with the small NOVA patch is expected, as it works around a missing feature in KVM. Regarding your SVM problem: It might be that with -cpu host Qemu/KVM advertises features which it doesn't implement and thus you end up in the double fault handler. I'll close this issue for now. If someone decides to investigate the SVM thing further, please open a new bug.

**Closed as completed by blitz** 2013-10-28 13:24 UTC
